### ISSUE TITLE
Error Name POSITIVE_FACE_PRESSURE

### ISSUE THREAD

**Issue by lorenzogracia** [KratosMultiphysics/GiDInterface#149]
After some checks I have realized that there is a typo in the name of the POSITIVE_FACE_PRESSURE (at least in the DamApplication) , there is and space after the word. Anyone that uses this variable, please check it. @KratosMultiphysics/structural-mechanics @KratosMultiphysics/solid-mechanics

**Comment by josep-m-carbonell** [comment]
You are right, who changed the name to "POSITIVE_FACE_PRESSURE " ?  No advise was given to all applications containing it,  and  it was done in the commits before the release...

**Comment by josep-m-carbonell** [comment]
@jginternational

**Comment by jginternational** [comment]
@lorenzogracia Right. there was an extra space (probably due to a Search and Replace automatic)

@josep-m-carbonell This was argued here #135

**Comment by josep-m-carbonell** [comment]
Well,  related to #135, it would be good to include all people affected by the desicion. POSITIVE or NEGATIVE, for a Kratos variable is only a confusing word taking into account that in solids and soild/fluids the PRESSURE has different sign conventions. POSITIVE_FACE and NEGATIVE_FACE is also a little bit arbitrary. I don't know if the definition of the normal of the surface geometry is going to have any influence in the sign of the assigned pressure, even if we write in the POSITIVE_FACE_PRESSURE variable, can the sign of the pressure change due to the numeration order of the surface mesh?

**Comment by pooyan-dadvand** [comment]
positive face pressure always applies in contrary to the normal. Isn't it?

**Comment by ipouplana** [comment]
Yes, according to the convention in #135, a positive face pressure points in the opposite sense of the normal. I think that if this is the convention, the GUI should tell the user through a help text or something similar...

**Comment by jginternational** [comment]
@ipouplana It can be explained in the help (tooltip) of the condition
