### ISSUE TITLE
Add Truss element to Structural

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#164]
We are adding the Truss element to the structural mechanics application.

As far as we understand, Truss and Beams have no available constitutive laws right now, so I'll need a running example (including mdpa, json and python files) to set up the scripts.

The perfect solution should be to create a constitutive law like LinearElasticTrussLaw and define it's parameters, both in GiD and Kratos, to assign these parameters to the elements

**Comment by RiccardoRossi** [comment]
hi @philbucher @KlausBSautter @AndreasWinterstein 

in order to make this to work with the structural mechanics we need to create two "fake" constitutive laws in the StructuralApplication. With "fake" i mean two empty classes derived from the ConstitutiveLaw and called (say) BeamConstitutiveLaw and TrussConstitutiveLaw.
As a stopgap, these CLs will be written in the material file, and then (for the moment) ignored by the elements. However this will allow us in the interface to tell which parameters are to be prescribed.

can u create these empty classes and expose them to python?

aside of this, did u make any progress with defining the LOCAL_AXES_* and using them as input?

**Comment by loumalouomega** [comment]
@jginternational with the base class the problem type works:
~~~~
{
    "properties" : [{
        "model_part_name" : "Parts_Parts_Auto1",
        "properties_id"   : 1,
        "Material"        : {
            "constitutive_law" : {
                "name" : "KratosMultiphysics.ConstitutiveLaw"
            },
            "Variables"        : {
                "DENSITY"       : 7850.0,
                "YOUNG_MODULUS" : 206900000000.0,
                "POISSON_RATIO" : 0.29,
                "KratosMultiphysics.StructuralMechanicsApplication.CROSS_AREA"    : 0.01
            },
            "Tables"           : {}
        }
    }]
}
~~~~

**Comment by jginternational** [comment]
Done, but it can not be a definitive solution, because we can not write "KratosMultiphysics.StructuralMechanicsApplication.CROSS_AREA" ("CROSS_AREA" is written instead of the full name)
