### ISSUE TITLE
Official/Developer applications in Release 5.1.xx

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#22]
To start with, I should know which **applications** (from the list) **should be deployed** in **official** mode:
- [ ] Solid Mechanics
    - [x] Structural Mechanics
- [x] Fluid Dynamics
    - [x] Embedded Fluid
    - [ ] Potential Fluid
- [x] Fluid Structure Interaction
- [ ] PFEM
- [ ] DAM
- [ ] Stenosis Wizard (Example)
- [x] DEM

The rest will be packed  **hidden** (A.K.A in **developer mode**)?

Find the [project](https://github.com/KratosMultiphysics/GiDInterface/projects/5)

**Once decided this**, we should determine what **parts of the official applications should be hidden** in the official mode (visible for developers only)

**Comment by pooyan-dadvand** [comment]
I would add the developer ones also. The question would be which feature goes to where!

**Comment by jginternational** [comment]
Ok, let me edit the comment. 
In a "developer" application, everything is visible if the user is in "developer mode"
We have to set which apps will be in official mode, and which part of these apps will be only shown in developer mode.

**Comment by rubenzorrilla** [comment]
Correct me if I'm wrong, but as far as I have understood, the idea is to pack all the apps but making some features only available in developer mode. 

Besides, it would be interesting to add some predefined examples directly available from each app interface like we did for the Mok benchmark in the FSI one (don't try it because at the moment is not working at all...).

**Comment by jginternational** [comment]
@rubenzorrilla you are right. But we'll need to check every app in "official" mode
