### ISSUE TITLE
Slip boundary conditions in subsubmodelparts.

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/GiDInterface#240]
@jginternational, we are all already aware of the slip boundary conditions problem, you cannot use more than one group to represent a skin condition that could be unfolded in a unique skin. This can be easily viewed in a slip channel problem, in where you need to save all the slip walls in a unique submodelpart.

Thus, our proposal is to let the user to set as slip groups as he wants and then save them as subsubmodelparts of a slip submodelpart (created by us). Then, the slip process is always applied to that "father" slip submodelpart, without considering the user groups.

@jginternational can this be done by modifying the Writing.tcl in the FluidApplication?

**Comment by jginternational** [comment]
This changes will fix a big problem, but I'm not sure if this implementation should be done in the GiD problemtype. Of course it's the main access point to the kratos applications, and any fix in the interface will satisfy most of the users, but one can run kratos without the GUI, and set several submodelparts as Slip conditions. 

In my opinion, these operations should be done inside the application, not in the user interface. Maybe adding to the projectparameters.json a list of submodelparts in the mdpa where the Slip process is applied, instead of looking for them in the full processes list can help, but moving to GiD this fix is not a good idea.

Once said this, it's not difficult to implement it.

**Comment by jginternational** [comment]
First point: I still think that this should be done in python/c++ side. Said this... let's play.

The main idea is to write everything related to a condition in nested submodelparts, instead of listed one after other.

Let's see it in an example:
Imagine that we have the Slip condition, and we apply it into 2 different groups. Group A contains triangles 1 and 2, Group B contains triangles 3 and 4 (see figure)
![image](https://user-images.githubusercontent.com/5918085/35823466-eb357a52-0aaf-11e8-908e-12b13bcb1549.png)

The current mdpa looks like:
```
Begin Nodes
    1   0.8626560000   1.6628800000   0.0000000000
    2   0.8626560000   0.7428149970  -0.0000000000
    ...
    8   0.8626560000   0.5051065000   2.0000000000
End Nodes

Begin Conditions WallCondition3D3N// GUI group identifier: GroupA
    1 0 1 2 3
    2 0 2 4 3
End Conditions

Begin Conditions WallCondition3D3N// GUI group identifier: GroupB
    1 0 1 2 3
    2 0 2 4 3
End Conditions

Begin SubModelPart Slip3D_GroupA // Group GroupA // Subtree Slip3D
    Begin SubModelPartNodes
         1
         2
         3
         4
    End SubModelPartNodes
    Begin SubModelPartConditions
        1
        2
    End SubModelPartConditions
End SubModelPart
Begin SubModelPart Slip3D_GroupB // Group GroupB // Subtree Slip3D
    Begin SubModelPartNodes
         5
         6
         7
         8
    End SubModelPartNodes
    Begin SubModelPartConditions
        3
        4
    End SubModelPartConditions
End SubModelPart
```
And the ProjectParameters.json file:

```javascript
{
"boundary_conditions_process_list": [
    {
        "python_module" : "apply_slip_process",
        "kratos_module" : "KratosMultiphysics.FluidDynamicsApplication",
        "process_name"  : "ApplySlipProcess",
        "Parameters"    : {
            "mesh_id"         : 0,
            "model_part_name" : "Slip3D_GroupA"
        }
    },{
        "python_module" : "apply_slip_process",
        "kratos_module" : "KratosMultiphysics.FluidDynamicsApplication",
        "process_name"  : "ApplySlipProcess",
        "Parameters"    : {
            "mesh_id"         : 0,
            "model_part_name" : "Slip3D_GroupB"
        }
    }
]}
```


The **PROPOSED mdpa** looks like:
```
Begin Nodes
    1   0.8626560000   1.6628800000   0.0000000000
    2   0.8626560000   0.7428149970  -0.0000000000
    ...
    8   0.8626560000   0.5051065000   2.0000000000
End Nodes

Begin Conditions WallCondition3D3N// GUI group identifier: GroupA
    1 0 1 2 3
    2 0 2 4 3
End Conditions

Begin Conditions WallCondition3D3N// GUI group identifier: GroupB
    1 0 1 2 3
    2 0 2 4 3
End Conditions

Begin SubModelPart Slip3D // Subtree Slip3D
    Begin SubModelPartNodes
         1
         2
         3
         4
         5
         6
         7
         8
    End SubModelPartNodes
    Begin SubModelPartConditions
        1
        2
        3
        4
    End SubModelPartConditions
    Begin SubModelPart Slip3D_GroupA // Group GroupA // Subtree Slip3D
        Begin SubModelPartNodes
             1
             2
             3
             4
        End SubModelPartNodes
        Begin SubModelPartConditions
            1
            2
        End SubModelPartConditions
    End SubModelPart
    Begin SubModelPart Slip3D_GroupB // Group GroupB // Subtree Slip3D
        Begin SubModelPartNodes
             5
             6
             7
             8
        End SubModelPartNodes
        Begin SubModelPartConditions
            3
            4
    End SubModelPartConditions
    End SubModelPart
End SubModelPart
```
And the ProjectParameters.json file:

```javascript
{
"boundary_conditions_process_list": [
    {
        "python_module" : "apply_slip_process",
        "kratos_module" : "KratosMultiphysics.FluidDynamicsApplication",
        "process_name"  : "ApplySlipProcess",
        "Parameters"    : {
            "model_part_name" : "Slip3D"
        }
    }
]}
```

As you can notice, we are applying the slip process to the 'grouped submodelpart', which contains the sum of all nodes and conditions of the groups. 
The only point to take into account is that **this process must not have parameters not intervals**, because we are grouping by process, so any parameter that differs from one group to another will not be printed.
Imagine this kind of submodelpart grouping applied to several inlet groups, instead of slip. We'll get a single submodelpart for several inlets, and we'll apply only once the inlet process. Which velocity should I take? and which time interval? It is not possible to group by conditions whose process has parameters.
Luckily, Slip process has no parameters, so there is no problem.

The bad part of this implementation is, of course, the **performance**, but as we say in Spanglish "from lost to the river".
Remember that we have to print conditions in tcl due to the renumbering

**Comment by RiccardoRossi** [comment]
We discussed internally and we would go for the solution of putting everything as a subsubmodelpart
