### ISSUE TITLE
Pull request #265 introduces errors in write properties of mdpa file

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/GiDInterface#270]
Now the mdpa for the solid mechanics and pfem is incorrect. The value of properties are not written and an indentation error appear in the "End Properties" row.

**Comment by rubenzorrilla** [comment]
Hi @josep-m-carbonell !

We also note that in the FluidDynamicsApp. We reported it to @jginternational and AFAIK he is working on that.

**Comment by josep-m-carbonell** [comment]
I have taken a look, changes concerning only to the structural app have been implemented in the common part of Kratos,  breaking all other apps.

**Comment by jginternational** [comment]
@josep-m-carbonell 
> I have taken a look, changes concerning only to the structural app have been implemented in the common part of Kratos, breaking all other apps.

This is not true. Changes are available for all apps and only Structural is using them at this moment. 

Every pull request with new functions can have bugs. In this case, the bug was a simple typography error. I accidentally deleted an argument in the print function after testing and before the commit.

**Comment by josep-m-carbonell** [comment]
Ok, thank you to solve the error.
