### ISSUE TITLE
Dem - Review example parameters

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#289]
The Dem example is running fine.

Please check if the default parameters are OK for running the example.

EXTRA:
The given examples are used as "test", but can also be used as Benchmark. So maybe we can create a new example for benchmarking

**Comment by maceligueta** [comment]
The following parameters work fine if the user meshes with a size of 0.2 m. The parameters depend strongly on the chosen mesh size, so it wold be great if Gid can propose 0.2, instead of 0.75 (which is a really big size for this geometry)
Inlet:

- diameter 0.1 instead of 1
- velocity direction 0, 0, -1 instead of 1, 0, 0
- color 2 (instead of 1)

Time parameters:

- time_step 1e-5 instead of 1e-6
- final time 20 s instead of 1 s
- search freq 20 instead of 50

Materials:

- Young 1e6 for the Inlet (instead of 1e5)
- Young 1e6 for the Part (instead of 1e5)

**Comment by jginternational** [comment]
@maceligueta Shouldn't we add a Bounding box in the example? Spheres keep falling into space due to gravity and at the end of the simulation they are far far away

**Comment by maceligueta** [comment]
Sure! I forgot to write this one, sorry.
Activate bounding box and set MinZ as -1.0. That's what I did.
