### ISSUE TITLE
[Release 6.0] Where is the presstresed membrane?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/GiDInterface#385]
![imagen](https://user-images.githubusercontent.com/19991680/40837039-4ad42082-6599-11e8-9f30-e0760060e99e.png)
![imagen](https://user-images.githubusercontent.com/19991680/40837079-6e489d7c-6599-11e8-83b0-71bcf9082094.png)

**Comment by loumalouomega** [comment]
It was added here 

https://github.com/KratosMultiphysics/GiDInterface/pull/318/files

**Comment by loumalouomega** [comment]
Ok, it is in developer mode, it is supposed to be in release

**Comment by jginternational** [comment]
Go to Model information > Solver Type and select Formfinding

**Comment by loumalouomega** [comment]
Yes, i did that

**Comment by loumalouomega** [comment]
![imagen](https://user-images.githubusercontent.com/19991680/40837907-40e60bc8-659c-11e8-8061-28436fd81ea8.png)

**Comment by loumalouomega** [comment]
[test.gid.zip](https://github.com/KratosMultiphysics/GiDInterface/files/2062465/test.gid.zip)

**Comment by philbucher** [comment]
Why does it only appear in FormFinding?

**Comment by loumalouomega** [comment]
And only in developer mode

**Comment by jginternational** [comment]
PRESTRESS_VECTOR is written in the materials json [as defined here](PRESTRESS_VECTOR)

and this is the error that kratos throws:

`"File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\KratosMultiphysics\kratos_globals.py", line 72, in GetVariable
    raise ValueError("\nKernel.GetVariable() ERROR: Variable {0} is unknown. Maybe you need to import the application where it is defined?\n".format(VarName))
ValueError: 
Kernel.GetVariable() ERROR: Variable PRESTRESS_VECTOR is unknown. Maybe you need to import the application where it is defined?
`

I'm looking for this variable, PRESTRESS_VECTOR , and seems to be MEMBRANE_PRESTRESS now, and it's a matrix instead of a vector

@annasophie91

**Comment by philbucher** [comment]
same problem as in #390: 
not merged yet, see https://github.com/KratosMultiphysics/Kratos/pull/2101

**Comment by jginternational** [comment]
So, if we want the membranes to work, we should add that PR to the release. Or remove the membranes

**Comment by jginternational** [comment]
Membranes will NOT be available in this release
@KratosMultiphysics/technical-committee
