### ISSUE TITLE
Release 7.0

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/GiDInterface#533]
Hello everyone,
        we need to ensure that what is in the "release version" of the GUI works corectly.

As a minimum we need to ensure that

- [x] FluidDynamics (body-fitted and embedded): @rubenzorrilla @jcotela
- [ ] StructuralMechanicsApplication: @loumalouomega @philbucher (...and please mention here who else you consider should be involved)
- [x] FSI: @rubenzorrilla 
- [x] Convection-diffusion, buoyancy and CHT: @rubenzorrilla 
- [ ] DEM: @maceligueta @GuillermoCasas 
- [ ] MPM: @bodhinandach 

this list is of course far from complete. please take the time to take a look into this and CC who should be involved

in particular @marcnunezc @inigolcanalejo is the potential flow interface ready for prime time?

please everyone feel free to discuss here what else should be tested for release

**Comment by jcotela** [comment]
What is the GiD version target in this case? Can we expect things to work for GiD 13? (I have not updated so far...)

**Comment by RiccardoRossi** [comment]
i think we should target 14

**Comment by jginternational** [comment]
I can not guarantee that main apps work fine on GiD 13 since GiD 14 was released several months ago (and the 13th release was done 3 years ago).

We have a pull request waiting #449 for setting 14 as minimum version.

GiD 13 users will have Kratos 6.0 still available

**Comment by pooyan-dadvand** [comment]
I think that its time to move to version 14 unless we have a serious blocker to do so

**Comment by marcnunezc** [comment]
Hi,

As for the PotentialFlowApp, it is currently not ready to be added to the release version of the GiD Interface (there's still work to be done regarding the 3D case). Do you agree @inigolcanalejo?

Regards,

**Comment by jginternational** [comment]
@KratosMultiphysics/all 

It's time to test you apps in the GUI

You can still use the master branch, since there is no additions for the release (I'll just remove the apps that wont be published)

Please report the bugs via issue!

**Comment by RiccardoRossi** [comment]
@KratosMultiphysics/technical-committee

**Comment by antonialarese** [comment]
@bodhinandach

**Comment by bodhinandach** [comment]
@antonialarese @rubenzorrilla Thanks! I am on it.

**Comment by jginternational** [comment]
### Good news everyone! 
@KratosMultiphysics/technical-committee 

I've been testing the problemtype in the latest GiD version for Linux 64 (14.1.0d) and it seems to work fine. @maceligueta I've notice a small issue in the transform with this GiD version that behaves different than the windows one, but I'll try to fix it.

We can go on with the testing there, so:

@KratosMultiphysics/all 
**LINUX USERS, please do your testings in the [14.1.0d of GiD]**(https://www.gidhome.com/download/developer-versions/linux64/)

I'm creating the release-7 branch soon to turn off the apps that will not be packed

Remember to fix all the bugs, or at least, create the issue here.
