### ISSUE TITLE
Define Element coordinate system

### ISSUE THREAD

**Issue by emanujoy** [KratosMultiphysics/GiDInterface#563]
I would like to model a structure of carbon-fiber reinforced plastic with Kratos Multiphysics.  I have successfully modeled the structure with GID and analyzed the structure with an isotropic material in Kratos. Now would like to use an anisotropic material using the following example: https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/tests/test_patch_test_shells_orthotropic.py
I am running into a problem checking the orientation of the elemental coordinate systems.  Is it possible to visualize them with GiD?  Is possible to reorient them? 
Thanks!

**Comment by jginternational** [comment]
Hope @escolano can help

**Comment by escolano** [comment]
Curves and surfaces have implicitly defined 'automatic local' axis, based on its normal and tangent respectively, and an arbitrary convention to set the other axis:
This is the GiD definition: 
[https://www.gidhome.com/documents/customizationmanual/APPENDIX%20B%20(classic%20problemtype%20system)/PROBLEMTYPE%20'CLASSIC'/CONFIGURATION%20FILES/Conditions%20file%20(.cnd)](url)

Automatic axes: 
For surfaces, this axes are calculated from the unitary normal N:
z'=N
if N is coincident with the global Y direction (Nx or Nz > some tolerance) then
  x'=Y x N / |Y x N|
else
  x'=Z x N / |Z x N|
y'=N x x'
z'=N
For lines, this axes are calculated from the unitary tangent T:
x'=T
if T is coincident with the global Z direction (Nx or Ny > some tolerance) then
  y'=Y x x' / |Y x x'|
else
  y'=Z x x' / |Z x x'|

z'=x' x y'

And these implicit axis could be assumed and used for example to draw an oriented symbol (to show the user graphically if the applied data is ok or not)
e.g. by current Kratos problemtype, based on 'CustomLib', with the <symbol> tag 
[](https://www.gidhome.com/documents/customizationmanual/PROBLEMTYPE%20SYSTEM/Data%20tree%20fields/PT_data/condition/symbol)

Have a look to the problemtye Kratos->Solid (currently the only kratos problemtype that implements the symbols feature), 
Load the  Solid->3D, and click the toolbar example 'Circular water tank'
it has a pressure load that is defined in local axes (the scalar pressure value is normal to the surface)
select Pressure in the tree, click the right-mouse button and select 'Draw symbols' in its contextual menu
It will show this, with the arrows of the pressure drawn based on these 'automatic' local axis.
![image](https://user-images.githubusercontent.com/39376606/55002184-72417980-4fd6-11e9-9d29-de3a04029808.png)

**Comment by escolano** [comment]
It is also possible to assign to the entities 'classical conditions' with an special #LA# local axis field
Kratos is defininig in kratos.cnd some of these conditions, but the windows to handle them are hidden and not pointed by any menu.
As trick, you can open the 'classical conditions window' writing this in the lower command line
Mescape Data Conditions CondWindow
![image](https://user-images.githubusercontent.com/39376606/55002533-13303480-4fd7-11e9-930e-ea026b4bd5fb.png)
Or there is also a more specialized window, based on these conditions, to be used as local axis only,
write this to open this local axis window:
-np- gid_groups_conds::local_axes_window
![image](https://user-images.githubusercontent.com/39376606/55002656-4b377780-4fd7-11e9-88bd-34e18aecec1d.png)
You can assign these local axis to the entities you want, and also draw them.
(when generating the mesh, the mesh entities will inherit this information attached to the geometry)
e.g. assigning a local axis 'automatic' to a surface of the previous model, and generating the mesh, you can draw these axis:
![image](https://user-images.githubusercontent.com/39376606/55002988-c7ca5600-4fd7-11e9-930b-40420ded0e47.png)

And there are commands to get/set this kind of information from Tcl scripting (and classical .bas templates), in order to be written as necessary in the calculation input file (the .mdpa of kratos)

**Comment by emanujoy** [comment]
Thank you @escolano for the response!
it is what i was searching for! 
I also tried to assign a new reference system and it works perfectly!
