### ISSUE TITLE
import mdpa in GiD

### ISSUE THREAD

**Issue by MagaFem** [KratosMultiphysics/GiDInterface#592]
I translated an Abaqus mesh with meshio to mdpa. How can i open this and give boundary conditions in GiD?

**Comment by rubenzorrilla** [comment]
Once you load the Kratos GUI in GiD, in the "Kratos" tab in the top ribbon bar you can select "Import MDPA" to load it.

**Comment by MagaFem** [comment]
Did not see, thanks. Importing and loading model possible. Boundary conditions dont work. Or Im missing something again?

**Comment by rubenzorrilla** [comment]
> Did not see, thanks. Importing and loading model possible. Boundary conditions dont work. Or Im missing something again?

This tool only imports the .mdpa, which contains the model geometry. To impose the BCs you will need to set the GiD groups to the geometrical entities of interest to then assign such groups to the BCs section of the Kratos tree.

**Comment by jginternational** [comment]
Hi @MagaFem 
The MDPA importer tool imports the mdpa, creates it's mesh and creates the groups according to the MDPA submodelparts. The BC must be assigned to the tree manually, but the groups are automatically created.

You can check it's implementation in:
https://github.com/KratosMultiphysics/GiDInterface/blob/master/kratos.gid/scripts/Controllers/MdpaImportMesh.tcl

**Comment by MagaFem** [comment]
I now have the problem that when trying to run this from GID.  MainKratos.py and the JSON files are not written. is it possible to read a mesh into GID, apply loads and BCs and then solve with kratos multiphysics?

**Comment by jginternational** [comment]
The process is always the same:

1. Draw or import a geometry
2. Apply loads and BC
3. Mesh 
4. Write files and Calculate (the rocket icon)

**Comment by MagaFem** [comment]
Thanks @jginternational!
Sorry, it was not clear. I am reading in a mesh that I want to analyze (and not draw new). Is this not possible?

**Comment by jginternational** [comment]
Well, thats possible for some apps.
For example, in Structural Mechanics app, you need to generate the mesh with GiD if you are using any Beam element, because in the meshing process GiD assigns the local axes to the linear elements

In most apps you can create the groups to apply the loads and conditions and assign mesh elements and nodes to them. 

Anyway, my recommendation is to **import the geometry** (not the mesh) from the abacus project.
Try to export it in ACIS, IGES or STEP format and import it into GiD
