### ISSUE TITLE
Various problems with GiD (sometimes in combination with Kratos Problemtype) under Linux

### ISSUE THREAD

**Issue by mpentek** [KratosMultiphysics/GiDInterface#630]
As a follow-up to #626 , it seems that there are way more bugs with GiD running on Linux than on Windows. Any input on why this is happening and how it could be remedied/improved? It seems that at least @loumalouomega and @AndreasWinterstein have experienced similar issues, some recently.

**Comment by AndreasWinterstein** [comment]
I also want to add that the GiD website is down since this morning.

**Comment by jginternational** [comment]
Well, step by step.

@AndreasWinterstein the website issue is due to the web is hosted in the university, and every year, in August, the whole UPC electric supply is switched off for a day for maintenance.

@mpentek the unix issue that some linux users are experiencing #626 is not fixable at kratos interface side. It's a GiD problem. (If you are experiencing the linux bug and try with another problemtype, like Examples/cmas2d_customlib, it also will fail).
The cause is that the linux manager is on medical leave, and hope that he is back in September. In this situation, the Windows manager has been the responsible to pack also the linux version... 
We have tried to reproduce the error on linux machines but it works fine.

**Comment by mpentek** [comment]
@jginternational crossing fingers that these problems are remedied in autumn
