### ISSUE TITLE
DEM wall for linear line elements

### ISSUE THREAD

**Issue by KlausBSautter** [KratosMultiphysics/GiDInterface#683]
Hi, I think I was using an old version of the Interface for the DEM App. Anyway here is my problem:

With the version, I was using I could create a DEM-FEM wall condition for a group with line elements and it created 
> RigidFace3D2N

 with the current interface, it creates

> RigidFace3D3N

automatically. How can I change this behavior? 

Klaus

**Comment by maceligueta** [comment]
Hi @KlausBSautter. Thanks for reporting. Just one question (due to my bad memory): in the old GUI, in 3D we allowed Line elements and they were called RigidFace3D2N?
This is just to state clearly what we want from the new GUI.
Right now @farrufat-cimne and myself are changing parts of the GUI, but the real expert is @jginternational , so I will keep him in the loop, understanding that this issue is quite urgent because it is blocking your work somehow.

**Comment by KlausBSautter** [comment]
@maceligueta yes I need the line elements as contact conditions for the protection nets. In the GUI you didn't need to specify the element, you just assigned a group to the dem-fem wall condition and if it contained only lines it created RigidFace3D2N.

**Comment by jginternational** [comment]
Hi @KlausBSautter 

Correct me if I'm wrong.
You are using DEM application in 3D and you want to apply the DEM-FEM-WALL condition to a group containing lines, right?

**Comment by KlausBSautter** [comment]
yes, exactly. Somehow this was working before

**Comment by jginternational** [comment]
Is this done?

**Comment by KlausBSautter** [comment]
yes, I guess. It works now. Thanks!
