### ISSUE TITLE
Error Opening Kratos Problem Type

### ISSUE THREAD

**Issue by rlrangel** [KratosMultiphysics/GiDInterface#905]
After some months without using GiD in my office PC, I started facing the error shown in the image below when opening the Kratos problem type.
The dialog with the error message shows up before the applications dialog is displayed.

I tried to uninstall GiD and install the newest developed version (16.1.1), cloned again the repository, re-created the links as explained in the tutorial, but it did not work.

![error_gid](https://user-images.githubusercontent.com/69159206/193574807-53a51fc0-7066-4941-818b-6c40d1025483.PNG)

**Comment by jginternational** [comment]
I don't know what is that X: unit 

Let's diagnose it. Open GiD and load kratos problemtype.
In the command bar (bottom) execute this sentence:
`-np- W [Kratos::GetLaunchConfigurationFile]``

And make a screenshot so I can help
![image](https://user-images.githubusercontent.com/5918085/193785107-807d70a9-2697-4fbe-91df-fd2ec37d529c.png)

**Comment by rlrangel** [comment]
Hi Javi,

If I try to open Kratos problemtype, the error shown in my previous message appears, and nothing else.
But if I close that dialog and execute the command you suggested, the following warning appears:

![image](https://user-images.githubusercontent.com/69159206/193798245-3eec423d-a0e2-448e-ae3a-8450e72cfc71.png)

**Comment by rlrangel** [comment]
An update on this.

The last commit where it was working well was this: https://github.com/KratosMultiphysics/GiDInterface/commit/4e1782a55c751d4c5cfd14a9e58c27204209af34

From the next commit, I start to have the problem:
https://github.com/KratosMultiphysics/GiDInterface/commit/9dcde3c0fb363071c0700300d1fab2a78f4226ea

**Comment by rlrangel** [comment]
Another update.

Between these two commits, a new file was created, which is where the error occurs: [kratos.gid/scripts/Launch.tcl.](https://github.com/KratosMultiphysics/GiDInterface/blob/master/kratos.gid/scripts/Launch.tcl)

In function _GetLaunchConfigurationFile_, it tries to get the environmental variable HOME.

However, in my PC this variable is set to directory X, which apparently does not exist.

For example, If I run "set HOME" in the command window, it says:
HOMEDRIVE=X:
HOMEPATH=\
HOMESHARE=\\masterdisc\personal

I still could not find a way to change these variables.

P.S.: I use Windows.

**Comment by escolano** [comment]
The problem is that in your Windows there is a environment variable named HOME with value "X:" and this unit really is not mapped in your computer.
(this is a common problem at CIMNE premises, our Windows machines starting usually map this unit letter X: to the network location \\masterdisc\users\your_user)
And this environment variable seem that is 'special' and don't appear or can be changed as usually.
Ask the systems to try to change this configuration.
you can overwrite the value of this environment variable in a console before start GiD, or inside GiD in Tcl before load the kratos problemtype, with a command like this
-np- set ::env(HOME) {C:\users\rrangel}
or some other valid path

or can modify the kratos-GUI file <GiD>\problemtypes\kratos.gid\scripts\Launch.tcl

proc Kratos::GetLaunchConfigurationFile { } {
    set new_dir [file join $::env(HOME) .kratos_multiphysics]
    set file [file join $new_dir launch_configuration.json]
    return [list $new_dir $file]
}

and instead $::env(HOME) in your local copy can write hardcoded you true user path, e.g. C:/users/rrangel
