### ISSUE TITLE
Compatibility of versions

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/GiDInterface#948]
![image](https://github.com/KratosMultiphysics/GiDInterface/assets/25640870/7619b299-e166-4ec0-b377-308cc4363ddb)

After updating the problemtype I've seen this message. I'm using GiD16.

If a change in the problemtype means purchasing a newer license or leads to the presence of annoying warnings, it may cause Kratos to loose interest for industry research. I was wondering if there is a guideline to deal with this situations. @KratosMultiphysics/kratos-core-team

**Comment by jginternational** [comment]
Hi @miguelmaso 

We only change major version on minimum GiD version requirements if there's a feature in a new GiD version that we need.

The last update, on march 2023, from 15th to 16th, was done because we needed the GiD internal python interpreter, only available in the developer version of GiD 16
